# Generated by Django 5.0.2 on 2024-04-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitenatacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InicioSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_fundo', models.ImageField(upload_to='thumb-site')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
