# Generated by Django 5.0.2 on 2024-04-02 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenatacao', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inscricao',
            new_name='Inscrito',
        ),
    ]
