# Generated by Django 5.0.2 on 2024-04-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenatacao', '0004_foto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InicioSetting',
            new_name='InicioAjuste',
        ),
    ]
