# Generated by Django 5.0.2 on 2024-04-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenatacao', '0005_rename_iniciosetting_inicioajuste'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InicioAjuste',
            new_name='Inicio',
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name': 'Configuração de Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='inicio',
            options={'verbose_name': 'Configuração de Início'},
        ),
        migrations.AlterModelOptions(
            name='inscrito',
            options={'verbose_name': 'Configuração de Inscritos'},
        ),
        migrations.AlterField(
            model_name='foto',
            name='descricao',
            field=models.TextField(max_length=3000),
        ),
    ]
