# Generated by Django 5.0.2 on 2024-04-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenatacao', '0006_rename_inicioajuste_inicio_alter_foto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={'verbose_name': 'Configuração de Portfolio Ajuste'},
        ),
        migrations.AlterModelOptions(
            name='inicio',
            options={'verbose_name': 'Configuração de Início Ajuste'},
        ),
        migrations.AlterModelOptions(
            name='inscrito',
            options={'verbose_name': 'Configuração de Inscritos Ajuste'},
        ),
    ]
