# Generated by Django 5.0.2 on 2024-04-15 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenatacao', '0007_alter_foto_options_alter_inicio_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrito',
            name='ativo',
        ),
    ]
